region                 = "us-east-1"
original_bucket_name   = "original-image-bucket123"
processed_bucket_name  = "resized-image-bucket123"
lambda_function_name   = "image_processor"
sns_topic_email        = "techops.buddy@gmail.com"
